### PR TITLE
initial state setting of ros nodes

### PR DESCRIPTION
**Pull request by minshallj**

### CODE REVIEW

**Comment by wzin** [comment]
Let's have this ros node do some other things that are missing:
- emit on_online message - when there's no internet
- emit on_offline message - when internetz came back
- emit on_inactive message - when /activity/active turned to False
- emit on_active message - when /activity/active turned to True

**Comment by zdenekmaxa** [comment]
- emit on_online message - when there's no internet
- emit on_offline message - when internetz came ba

emission of these messages is in the realm of the lg_offliner ros node.
also, lg_offliner ros node provides a service which returns True/False when offline/online.

never the less, this initial state mem node and lg_offliner will need to talk to each other one way or other.

**Comment by wzin** [comment]
test

**Comment by wzin** [comment]
test

**Pull request merged**
